name: CI

on:
  pull_request:
    branches: ['main', 'dev']

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        command: ['build', 'build-storybook']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node.js 및 NPM 설치
        uses: ./.github/actions/install

      - run: npm run ${{ matrix.command }}

      - name: Build React
        run: npm run build --if-present
